remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/

navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/

include:
  - _pages

author:
  name: "Sandra R. Babyale"
  avatar: "/assets/images/profile_pic.jpg"
  bio: "PhD researcher in wildfire smoke modeling, data assimilation, and computational mathematics."

  location: "Boise, ID"
  email: "sandrababyale@gmail.com"
  github: "BabyaleSandra"
  scholar: "your-scholar-id"  # optional
  orcid: "your-orcid-id"      # optional
