remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/

navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/

