remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: "Sandra R. Babyale"
description: "PhD researcher in wildfire smoke modeling, data assimilation, and computational mathematics"
url: "https://babyalesandra.github.io"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/

main:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Presentations"
    url: /presentations/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Students"
    url: /students/
  - title: "Projects"
    url: /projects/

header:
  nav: "main"

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: ""
